// <auto-generated />
using System;
using ArchiveData.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArchiveData.Migrations.MySqlDB
{
    [DbContext(typeof(MySqlDBContext))]
    [Migration("20210812113001_DateTimeToDouble2")]
    partial class DateTimeToDouble2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("ArchiveData.Model.ArchivedInputNotification", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("AcknowledgmentTimeStampUtc")
                        .HasColumnType("double");

                    b.Property<string>("ClientId")
                        .HasColumnType("varchar(36)");

                    b.Property<Guid>("EventDefinitionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EventTargetId")
                        .HasColumnType("char(36)");

                    b.Property<double>("SourceEventTimeStampUtc")
                        .HasColumnType("double");

                    b.HasKey("EventId");

                    b.HasIndex("EventDefinitionId");

                    b.ToTable("ArchivedInputNotifications");
                });

            modelBuilder.Entity("ArchiveData.Model.InputNotificationEventDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TermType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("InputNotificationEventDefinitionEntities");
                });

            modelBuilder.Entity("ArchiveData.Model.InputNotificationEventEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("AcknowledgmentTimeStampUtc")
                        .HasColumnType("double");

                    b.Property<string>("ClientId")
                        .HasColumnType("varchar(36)");

                    b.Property<Guid>("EventDefinitionId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("EventTargetId")
                        .HasMaxLength(36)
                        .HasColumnType("char(36)");

                    b.Property<double>("SourceEventTimeStampUtc")
                        .HasColumnType("double");

                    b.HasKey("EventId");

                    b.HasIndex("EventDefinitionId");

                    b.HasIndex(new[] { "SourceEventTimeStampUtc" }, "IX_SourceEventTimeStampUTC");

                    b.ToTable("InputNotificationEventEntities");
                });

            modelBuilder.Entity("ArchiveData.Model.ArchivedInputNotification", b =>
                {
                    b.HasOne("ArchiveData.Model.InputNotificationEventDefinitionEntity", "EventDefinition")
                        .WithMany()
                        .HasForeignKey("EventDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventDefinition");
                });

            modelBuilder.Entity("ArchiveData.Model.InputNotificationEventEntity", b =>
                {
                    b.HasOne("ArchiveData.Model.InputNotificationEventDefinitionEntity", "EventDefinition")
                        .WithMany()
                        .HasForeignKey("EventDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventDefinition");
                });
#pragma warning restore 612, 618
        }
    }
}
