// <auto-generated />
using System;
using ArchiveData.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArchiveData.Migrations
{
    [DbContext(typeof(SqlServerDBContext))]
    [Migration("20210805221045_AddedConstraints")]
    partial class AddedConstraints
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArchiveData.Model.ArchivedInputNotification", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AcknowledgmentTimeStampUtc")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("ClientId")
                        .HasMaxLength(36)
                        .HasColumnType("CHAR(36)");

                    b.Property<Guid>("EventDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventTargetId")
                        .HasMaxLength(36)
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("SourceEventTimeStampUtc")
                        .HasColumnType("smalldatetime");

                    b.HasKey("EventId");

                    b.HasIndex("EventDefinitionId");

                    b.ToTable("ArchivedInputNotifications");
                });

            modelBuilder.Entity("ArchiveData.Model.InputNotificationEventDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TermType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InputNotificationEventDefinitionEntities");
                });

            modelBuilder.Entity("ArchiveData.Model.InputNotificationEventEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AcknowledgmentTimeStampUtc")
                        .HasColumnType("smalldatetime");

                    b.Property<string>("ClientId")
                        .HasMaxLength(36)
                        .HasColumnType("CHAR(36)");

                    b.Property<Guid>("EventDefinitionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EventTargetId")
                        .HasMaxLength(36)
                        .HasColumnType("CHAR(36)");

                    b.Property<DateTime>("SourceEventTimeStampUtc")
                        .HasColumnType("smalldatetime");

                    b.HasKey("EventId");

                    b.HasIndex("EventDefinitionId");

                    b.HasIndex(new[] { "SourceEventTimeStampUtc" }, "IX_SourceEventTimeStampUTC");

                    b.ToTable("InputNotificationEventEntities");
                });

            modelBuilder.Entity("ArchiveData.Model.ArchivedInputNotification", b =>
                {
                    b.HasOne("ArchiveData.Model.InputNotificationEventDefinitionEntity", "EventDefinition")
                        .WithMany()
                        .HasForeignKey("EventDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventDefinition");
                });

            modelBuilder.Entity("ArchiveData.Model.InputNotificationEventEntity", b =>
                {
                    b.HasOne("ArchiveData.Model.InputNotificationEventDefinitionEntity", "EventDefinition")
                        .WithMany()
                        .HasForeignKey("EventDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventDefinition");
                });
#pragma warning restore 612, 618
        }
    }
}
